pipeline {
    agent any

    environment {
        PYTHON = 'python3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/AustinMusuya/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Setup Python Env') {
            steps {
                // ShiningPanda virtualenv
                withPythonEnv('/tmp/venv') {
                    sh '''
                        python3 -m venv venv
                        source venv/bin/activate
                        pip3 install --upgrade pip
                        pip3 install -r messaging_app/requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source venv/bin/activate
                    pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
